"use strict";

/**
 * (C) Copyright Zachary Martin 2018.
 * Use, modification and distribution are subject to the
 * Boost Software License:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */




export class Flt {

  private f: float;

  constructor(f: float) {
    this.f = f;
  }

  public abs(): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public acos(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public acosh(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public asin(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public asinh(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public atan(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public atanh(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public cbrt(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public ceil(): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public ceilI(): Int {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public cos(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public cosh(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public divBy(divisor: Flt | Int | number | string, prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public divide(dividend: Flt | Int | number | string, prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public equals(y: Flt | Int | number): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public exp(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public expm1(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public floor(): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public floorI(): Int {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public gt(y: Flt | Int | number): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public gte(y: Flt | Int | number): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isEven(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isFinite(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isInteger(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isNaN(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isNegative(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isNEGATIVE_INFINITY(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isOdd(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isOne(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isPositive(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isPOSITIVE_INFINITY(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public isZero(): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public ln(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public log(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public log1p(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public log2(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public log10(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public logBase(base: Flt | Int | number | string, prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public lt(y: Flt | Int | number): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public lte(y: Flt | Int | number): boolean {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public minus(y: Flt | Int | number | string, prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public mod(
    y: Flt | Int | number | string,
    type?: "euclidean" | "trunc" | "ceil" | "floor" | "round",
    prec?: P | null | undefined
  ): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public neg(): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public plus(y: Flt | Int | number | string, prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public reciprocal(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public root(degree: Flt | Int | number | string, prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public round(): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public roundI(): Int {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public sin(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public sinh(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public sqrt(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public squared(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public tan(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public tanh(prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public times(y: Flt | Int | number | string, prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public toJSON(): string {
    return JSONFlt.stringify(this.f);
  }

  public toNumber(): number {
    return Core.floatToNumber(this.f);
  }

  public toPow(exponent: Flt | Int | number | string, prec?: P | null | undefined): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public toString(
    radix?: number | null | undefined,
    maxPrecision?: number | null | undefined
  ): string {
    return StringWriter.toStr(this.f, radix, maxPrecision);
  }

  public trunc(): Flt {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }

  public truncI(): Int {
    // TODO: implement this function
    throw new Error("this method is not implemented yet");
  }


  public static getFloat(x: Flt): float { return x.f; }

  public static instance(x: any): x is Flt {
    return typeof x === "object" && x !== null && Core.instance(x.f) &&
      typeof x.abs === "function" && typeof x.isPOSITIVE_INFINITY === "function";
  }
}

import {float} from "../interfaces/float";

import {Int as IntAlias} from "./Int";
export type Int = IntAlias;

import {Core as CoreAlias} from "../core/Core";
const Core = CoreAlias;

import {P as PAlias} from "../core/P";
export type P = PAlias;

import {ArgHandler as ArgHandlerAlias} from "./ArgHandler";
const ArgHandler = ArgHandlerAlias;

import {JSONFlt as JSONFltAlias} from "./JSONFlt";
const JSONFlt = JSONFltAlias;

import {StringWriter as StringWriterAlias} from "../core/StringWriter";
const StringWriter = StringWriterAlias;