"use strict";

/**
 * (C) Copyright Zachary Martin 2018.
 * Use, modification and distribution are subject to the
 * Boost Software License:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */


export class IntUtil {
  public static className: string;
  public static constructorInt;
  public static methodNames: Array<string>;

  public static init0(): void {
    IntUtil.className = "IntUtil";
  }

  public static init(): void {
    class Int {
      constructor(private readonly i: int) {}
      public static getint(a: Int): int {
        return a.i;
      }
    }

    for (let fw of Library.getAllIntMethodFWs()) {
      Int.prototype[fw.name] = fw.method();
    }

    IntUtil.constructorInt = Int;
    IntUtil.getint = Int.getint;
    IntUtil.methodNames = Library.getAllIntMethodNames();
  }

  public static createInt(i: int): Int {
    return new IntUtil.constructorInt(i);
  }

  public static isInt(x: any): x is Int {
    if (typeof x === "undefined") {
      return false;
    }

    if (x instanceof IntUtil.constructorInt) {
      return true;
    }

    if (Core.instanceI(x.i)) {
      for (let methodName of IntUtil.methodNames) {
        if (typeof x[methodName] !== "function") {
          return false;
        }
      }

      return true;
    }

    return false;
  }

  public static getint(a: Int): int {
    return IntUtil.constructorInt.getint(a);
  }


  public static dependencies(): Set<Class> {
    return new Set([
      Core, Library,
    ]);
  }
}


// *** imports come at end to avoid circular dependency ***

// interface/type imports
import {int} from "../interfacesAndTypes/int";
import {Class} from "../interfacesAndTypes/Class";


// functional imports
import {Core as CoreAlias} from "../core/Core";
const Core = CoreAlias;

import {Library as LibraryAlias} from "../core/Library";
const Library = LibraryAlias;