"use strict";

/**
 * (C) Copyright Zachary Martin 2018.
 * Use, modification and distribution are subject to the
 * Boost Software License:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */


export class OMEGA {
  public static className: string;

  public static init0(): void {
    OMEGA.className = "OMEGA";
  }

  private static _value: float;
  private static _baseDigits: number;

  public static value(p: P): float {
    if (typeof OMEGA._baseDigits === "undefined" || OMEGA._baseDigits < p.baseDigits) {
      OMEGA._value = OMEGA.calculate(p);
      OMEGA._baseDigits = p.baseDigits;
    }

    return OMEGA._value;
  }

  private static calculate(p: P): float {
    const initialGuess = typeof OMEGA._baseDigits === "undefined" ||
    OMEGA._baseDigits < 3 ?
      Core.numberToFloatUnchecked(0.567143290409783873)
      :
      OMEGA._value;
    let val = initialGuess;
    let oldVal: float;

    for(let i = 0; i < p.quadraticConvergenceSteps; i++) {
      oldVal = val;
      val = Basic.divideFF(
        Basic.addFF(C.F_1, val, p),
        Basic.addFF(C.F_1, Exp.f(val, p), p),
        p
      );
      if (Comparison.lt(
              Sign.absF(Basic.subtractFF(val, oldVal, p)),
              Basic.multiplyFF(val, p.epsilon, p)
      )) {
        break;
      }
    }

    return val;
  }


  // class dependencies
  public static dependencies(): Set<Class> {
    return new Set([
      C, Sign, Core, Comparison, Basic, Exp,
    ]);
  }
}


// *** imports come at end to avoid circular dependency ***

// interface/type imports
import {float} from "../interfacesAndTypes/float";
import {Class} from "../interfacesAndTypes/Class";

import {P as PAlias} from "../dataTypes/P";
export type P = PAlias;


// functional imports
import {C as CAlias} from "./C";
const C = CAlias;

import {Sign as SignAlias} from "../basicFunctions/Sign";
const Sign = SignAlias;

import {Core as CoreAlias} from "../core/Core";
const Core = CoreAlias;

import {Comparison as ComparisonAlias} from "../basicFunctions/Comparison";
const Comparison = ComparisonAlias;

import {Basic as BasicAlias} from "../basicFunctions/Basic";
const Basic = BasicAlias;

import {Exp as ExpAlias} from "../basicFunctions/Exp";
const Exp = ExpAlias;

