"use strict";

/**
 * (C) Copyright Zachary Martin 2018.
 * Use, modification and distribution are subject to the
 * Boost Software License:
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */


export class Hybol {
  // class constants
  public static SMALL_ARG_CUTOFF: float;

  public static init1(): void {
    Hybol.SMALL_ARG_CUTOFF = RATIO.value(
      1,
      100,
      PREC.getPFromBaseDigits(3)
    );
  }

  public static sinh(x: float, p: P): float {
    if (Comparison.isFinite(x)) {
      if (Comparison.lte(Sign.absF(x), Hybol.SMALL_ARG_CUTOFF)) {
        return Hybol.taylorSeriesSinh(x, p);
      } else {
        return Hybol.sinhFromExp(x, p);
      }
    } else if (Comparison.isPOSITIVE_INFINITY(x)) {
      return C.F_POSITIVE_INFINITY;
    } else if (Comparison.isNEGATIVE_INFINITY(x)) {
      return C.F_NEGATIVE_INFINITY;
    } else { // x === NaN
      throw new NaNError("Hybol", "sinh", "x");
    }
  }

  public static cosh(x: float, p: P): float {
    if (Comparison.isFinite(x)) {
      return Hybol.coshFromExp(x, p);
    } else if (Comparison.isPOSITIVE_INFINITY(x) || Comparison.isNEGATIVE_INFINITY(x)) {
      return C.F_POSITIVE_INFINITY;
    } else { // x === NaN
      throw new NaNError("Hybol", "cosh", "x");
    }
  }

  public static tanh(x: float, p: P): float {
    if (Comparison.isNaN(x)) {
      throw new NaNError("Hybol", "tanh", "x");
    } else {
      if (Comparison.lte(Sign.absF(x), Hybol.SMALL_ARG_CUTOFF)) {
        const sinh = Hybol.taylorSeriesSinh(x, p);
        const cosh = Hybol.coshFromExp(x, p);
        return Basic.divideFF(sinh, cosh, p);
      } else {
        return Hybol.tanhFromExp(x, p); // +/- infinity cases handled correctly here
      }
    }
  }

  public static acosh(x: float, p: P): float {
    if (Comparison.isFinite(x) && Comparison.gteOne(x)) {
      return Acosh.imp(x, p);
    } else if (Comparison.isPOSITIVE_INFINITY(x)) {
      return C.F_POSITIVE_INFINITY;
    } else if (Comparison.isNaN(x)) {
      throw new NaNError("Hybol", "acosh", "x");
    } else { // x is finite and < 1 or -Infinity
      throw new DomainError(
        "Hybol",
        "acosh",
        {x: {value: x, expectedType: "float"}},
        "The acosh function is only defined for values greater than or equal to 1."
      );
    }
  }

  public static asinh(x: float, p: P): float {
    if (Comparison.isFinite(x)) {
      return Asinh.imp(x, p);
    } else if (Comparison.isPOSITIVE_INFINITY(x)) {
      return C.F_POSITIVE_INFINITY;
    } else if (Comparison.isNEGATIVE_INFINITY(x)) {
      return C.F_NEGATIVE_INFINITY;
    } else { // x === NaN
      throw new NaNError("Hybol", "asinh", "x");
    }
  }

  public static atanh(x: float, p: P): float {
    if (Comparison.isFinite(x) && Comparison.gt(x, C.F_NEG_1) && Comparison.ltOne(x)) {
      return Atanh.imp(x, p);
    } else if (Comparison.isOne(x)) {
      return C.F_POSITIVE_INFINITY;
    } else if (Comparison.isNegativeOne(x)) {
      return C.F_NEGATIVE_INFINITY;
    } else if (Comparison.isNaN(x)) {
      throw new NaNError("Hybol", "atanh", "x");
    } else { // x is finite and < -1 or > 1
      throw new DomainError(
        "Hybol",
        "atanh",
        {x: {value: x, expectedType: "float"}},
        "The atanh function is only defined for values between -1 and 1 inclusive."
      );
    }
  }


  // ********************* support functions ************************************

  private static taylorSeriesSinh(x: float, p: P): float {
    const xSquared = Basic.squareF(x, p);
    let termNum = x;
    let termDenom = C.F_1;
    let fact = {value: C.F_1, index: 1, nextIndex: 3};
    let sumNum =  termNum;
    let sumDenom = termDenom;
    let sntd: float;
    let sdtn: float;
    let absEpsTimesSNTD: float;
    let keepGoing = true;

    while(keepGoing) {
      termNum = Basic.multiplyFF(termNum, xSquared, p);
      fact.nextIndex = fact.index + 2;
      FactorialTable.calcFact(fact, p);
      termDenom = fact.value;

      sntd = Basic.multiplyFF(sumNum, termDenom, p);
      sdtn = Basic.multiplyFF(sumDenom, termNum, p);
      absEpsTimesSNTD = Sign.absF(Basic.multiplyFF(p.epsilon, sntd, p));

      if (Comparison.gte(absEpsTimesSNTD, Sign.absF(sdtn))) { keepGoing = false; }

      sumNum = Basic.addFF(sntd, sdtn, p);
      sumDenom = Basic.multiplyFF(sumDenom, termDenom, p);
    }

    return Basic.divideFF(sumNum, sumDenom, p);
  }

  /**
   * uses the formula for sinh(x):
   *
   *             exp(x) - exp(-x)
   * sinh(x) =  ------------------
   *                    2
   */
  private static sinhFromExp(x: float, p: P): float {
    const expX = Exp.f(x, p);
    const expNegX = Basic.reciprocalF(expX, p);

    return Basic.multiplyFF(C.F_ONE_HALF, Basic.subtractFF(expX, expNegX, p), p);
  }

  /**
   * uses the formula for cosh(x):
   *
   *            exp(x) + exp(-x)
   * cosh(x) = ------------------
   *                   2
   */
  private static coshFromExp(x: float, p: P): float {
    const expX = Exp.f(x, p);
    const expNegX = Basic.reciprocalF(expX, p);

    return Basic.multiplyFF(C.F_ONE_HALF, Basic.addFF(expX, expNegX, p), p);
  }

  /**
   * uses the formula for tanh(x):
   *
   *            1 - exp(-2x)
   * tanh(x) = --------------
   *            1 + exp(-2x)
   */
  private static tanhFromExp(x: float, p: P): float {
    const expNeg2X = Exp.f(Basic.multiplyFF(C.F_NEG_2, x, p), p);

    if (Comparison.lt(expNeg2X, p.epsilon)) {
      return C.F_1;
    } else if (Comparison.gt(expNeg2X, p.maxSafeInt)) {
      return C.F_NEG_1;
    } else {
      return Basic.divideFF(
        Basic.subtractFF(C.F_1, expNeg2X, p),
        Basic.incF(expNeg2X, p),
        p
      );
    }
  }
}


// *** imports come at end to avoid circular dependency ***

import {float} from "../interfaces/float";

import {C as CAlias} from "../constants/C";
const C = CAlias;

import {Sign as SignAlias} from "./Sign";
const Sign = SignAlias;

import {Comparison as ComparisonAlias} from "./Comparison";
const Comparison = ComparisonAlias;

import {Basic as BasicAlias} from "./Basic";
const Basic = BasicAlias;

import {FactorialTable as FactorialTableAlias} from "../constants/FactorialTable";
const FactorialTable = FactorialTableAlias;

import {Exp as ExpAlias} from "./Exp";
const Exp = ExpAlias;

import {RATIO as RATIOAlias} from "../constants/RATIO";
const RATIO = RATIOAlias;

import {Acosh as AcoshAlias} from "../boostPorts/special_functions/acosh";
const Acosh = AcoshAlias;

import {Asinh as AsinhAlias} from "../boostPorts/special_functions/asinh";
const Asinh = AsinhAlias;

import {Atanh as AtanhAlias} from "../boostPorts/special_functions/atanh";
const Atanh = AtanhAlias;

import {NaNError as NaNErrorAlias} from "../errors/NaNError";
const NaNError = NaNErrorAlias;

import {DomainError as DomainErrorAlias} from "../errors/DomainError";
const DomainError = DomainErrorAlias;

import {P as PAlias} from "../dataTypes/P";
export type P = PAlias;

import {PREC as PRECAlias} from "../constants/PREC";
const PREC = PRECAlias;